Repository ubsuny/CP1-24-HW6, pull requests merged in 2024-11, with the labels that each got.

#17 Added a Pull request template
  docs/pull_request_template.md
Labels: Maintainer

#24 Added the pytest fixtures
  test_preparation.py
Labels: Algorithm/subalgorithm

#20 2D fft / inverse fft calculating the actual frequency
  preparation.py
  test_preparation.py
Labels: python

#28 A function that reads in the pickle files from the data collection task and returns a pandas DataFrame
  preparation.py
  test_preparation.py
Labels: python

#30 Remove Periodic Behavior
  preparation.py
  test_preparation.py
Labels: python

#36 Cleaned up Image
  data_analysis.ipynb
Labels: Algorithm/subalgorithm

#42 Cleaning image (cube grid top)
  data_analysis.ipynb
Labels: python
